spring.application.name=product-service
server.port=8001

spring.datasource.url=jdbc:postgresql://localhost/db_product
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.locations=classpath:db/migration